// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    B: typeof import('./src/components/b/index.vue')['default']
    C: typeof import('./src/components/c/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    PageA1: typeof import('./src/components/a/pageA1.vue')['default']
    PageA2: typeof import('./src/components/a/pageA2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
